PACKAGE_NAME="silk-guardian"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="silk"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
AUTOINSTALL="yes"
